### ISSUE TITLE
ERROR:  only heap AM is supported

### ISSUE THREAD

**Issue by AlanduzzZ** [adjust/pg_cryogen#4] opened 2020-08-10 03:19 UTC
I got an error when using it with timescaledb.

PostgreSQL Version: 12.3
TimescaleDB Version: 1.7.0
OS Version: CentOS 7.6
Kernel Version: 5.7.3-1.el7.elrepo.x86_64

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_cryogen;

CREATE TABLE "public"."log" (
  "time" timestamptz(6) NOT NULL,
  "device_id" TEXT NOT NULL,
  "message_id" integer NOT NULL,
  "project_id" TEXT NOT NULL,
  "createtime" timestamp(6) NOT NULL,
  "service_type" integer NOT NULL,
  "message_type" integer NOT NULL,
  "data_type" TEXT NOT NULL,
  "metrics_name" TEXT NOT NULL,
  "metrics_value" TEXT NOT NULL
) using pg_cryogen;

SELECT create_hypertable('log', 'time', chunk_time_interval => interval '1 hours', create_default_indexes => false);
ERROR:  only heap AM is supported
SQL State: 0A000

Please let me know if there is a problem with my usage. Thanks~

**Comment by zilder** [comment] 2020-08-10 13:55
Hi @imalandu,

The problem is that `timescaledb` uses internally postgres' `heap_getnext` function which is part of the heap access method and cannot be used to access other storages (including `pg_cryogen`). Unless `timescaledb` adopts a higher level API to access storages (`table_scan_getnextslot` etc) there is nothing can be done.

Aside from that i'm still not sure it'll work well with `pg_cryogen`. `pg_cryogen` works well when there is a batched sequential writes into a single table at a time (otherwise it might waste a lot of space). I'm not familiar with `timescaledb` that well but can assume it routes tuples to partitions based on some key. If partition key values are not monotonic `pg_cryogen` might be ridiculously inefficient. If they are, then it might work.

I close this issue as `pg_cryogen` does not cause the error.

**Closed as completed** 2020-08-10 13:56 UTC
